/* =========================================================
   RETAIL ANALYSIS PROJECT – SQL QUERIES
   Database: retail_analysis
   ========================================================= */


/* 1. View all customers */
SELECT * 
FROM customers;


/* 2. View all products */
SELECT * 
FROM products;


/* 3. View all orders with customer name and product name */
SELECT 
    o.order_id,
    c.customer_name,
    p.product_name,
    o.quantity,
    o.order_date
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN products p ON o.product_id = p.product_id;


/* 4. Find the total amount spent by each customer */
SELECT 
    c.customer_name,
    SUM(pay.amount) AS total_spent
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN payments pay ON o.order_id = pay.order_id
GROUP BY c.customer_name;


/* 5. Find the total number of orders placed by each customer */
SELECT 
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_name;


/* 6. Find the total revenue generated by each product */
SELECT 
    p.product_name,
    SUM(pay.amount) AS total_revenue
FROM products p
JOIN orders o ON p.product_id = o.product_id
JOIN payments pay ON o.order_id = pay.order_id
GROUP BY p.product_name;


/* 7. Find the total revenue generated by each product category */
SELECT 
    p.category,
    SUM(pay.amount) AS category_revenue
FROM products p
JOIN orders o ON p.product_id = o.product_id
JOIN payments pay ON o.order_id = pay.order_id
GROUP BY p.category;


/* 8. Find the total amount received by each mode of payment */
SELECT 
    payment_mode,
    SUM(amount) AS total_amount
FROM payments
GROUP BY payment_mode;


/* 9. Find the customers who have paid using Cash */
SELECT DISTINCT
    c.customer_name
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN payments pay ON o.order_id = pay.order_id
WHERE pay.payment_mode = 'Cash';


/* 10. Find all orders placed in the current year */
SELECT *
FROM orders
WHERE YEAR(order_date) = YEAR(CURDATE());


/* 11. Find the top 3 customers based on total spending */
SELECT 
    c.customer_name,
    SUM(pay.amount) AS total_spent
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN payments pay ON o.order_id = pay.order_id
GROUP BY c.customer_name
ORDER BY total_spent DESC
LIMIT 3;


/* 12. Find customers who have never placed an order */
SELECT 
    c.customer_name
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;


/* 13. Find the average order value */
SELECT 
    AVG(amount) AS avg_order_value
FROM payments;


/* 14. Find customers whose total spending is greater than average order value */
SELECT 
    c.customer_name,
    SUM(pay.amount) AS total_spent
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN payments pay ON o.order_id = pay.order_id
GROUP BY c.customer_name
HAVING total_spent > (
    SELECT AVG(amount) FROM payments
);


/* 15. Find the most frequently ordered products */
SELECT 
    p.product_name,
    SUM(o.quantity) AS total_quantity
FROM products p
JOIN orders o ON p.product_id = o.product_id
GROUP BY p.product_name
ORDER BY total_quantity DESC;
